version: "3.9"
services:
  bot:
    build:
      context: .
      dockerfile: ./docker/bot/Dockerfile
    container_name: bot
    env_file: .env
    networks:
      - magic_helper_network

  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    container_name: nginx_bot
    depends_on:
      - bot
    ports:
      - 80:80
    networks:
      - magic_helper_network

networks:
  magic_helper_network:
    driver: bridge
    name: magic_helper_network
