version: "3.9"
services:
  bot:
    build:
      context: .
      dockerfile: ./docker/bot/Dockerfile
    container_name: bot
    env_file: .env
    ports:
      - 7777:7777
    networks:
      - magic_helper_network

networks:
  magic_helper_network:
    driver: bridge
    name: magic_helper_network
